apiVersion: v1
kind: Pod
metadata:
  name: test
  namespace: test
spec:
  containers:
  - name: test
    image: busybox
    resources:
      limits:
        memory: "1Gi"
        cpu: "200m"
      requests:
        memory: "600Mi"
        cpu: "100m"
